#!/bin/bash
dnf install -y git
git clone https://github.com/Skav0/Multi-tier-Web-Application-hosted-in-AWS.git
dnf install -y httpd
systemctl start httpd
systemctl enable httpd
mkdir /var/www/html/
mv /Multi-tier-Web-Application-hosted-in-AWS/index.html /var/www/html